### ISSUE TITLE
gimp_qt fails to build with qt-5.11.0

### ISSUE THREAD

**Issue by zarniwhoop73** [c-koi/gmic-qt#43]
src/Widgets/SearchFieldWidget.cpp: In constructor 'SearchFieldWidget::SearchFieldWidget(QWidget*)':
src/Widgets/SearchFieldWidget.cpp:52:69: error: no matching function for call to 'SearchFieldWidget::connect(QAction*&, const char [17], QLineEdit*&, const char [9])'
   connect(_action, SIGNAL(triggered(bool)), _lineEdit, SLOT(clear()));
                                                                     ^
Apparently there have been a lot of API changes in 5.11. The attached
[gmic-qt-5.11.txt](https://github.com/c-koi/gmic-qt/files/2065581/gmic-qt-5.11.txt)

 patch fixes it on 5.11, and I hope it will not break on older versions.
